#!/bin/bash

unset branch

if [ "${2}" == merge ] ; then
    branch=$( sed -ne "1 {s/^[^']*'\([^']*\)'.*\$/\1/;p;}" "${1}" )
else
    branch=$( git symbolic-ref --short HEAD )
fi

if [[ "${branch}" =~ infra[[:digit:]]{1,}$ ]] ; then
    sed -i -e "1 s/^/INFRA-${branch##*infra}: /;" "${1}"
fi
